name: AlGaN-medium-mpa-0
#foundation_model: /home/vol02/scarf562/playground/ml/models/mace-mp-0b3-medium.model  
foundation_model: /Users/brunocamino/Desktop/UCL/mace_benchmark/models/mace-mpa-0-medium.model
#foundation_model: medium-mpa-0
multiheads_finetuning: True
foundation_filter_elements: True
foundation_model_readout: True
loss: universal
heads:
 pbe:
   train_file: AlGaN-train.xyz
   valid_file: AlGaN-valid.xyz
   test_file: AlGaN-test.xyz
   E0s: isolatedAtom
pt_train_file: mp
num_samples_pt: 100000
energy_weight: 1.0
forces_weight: 10.0
stress_weight: 10.0
stress_key: dft_stress
energy_key: dft_energy
forces_key: dft_forces
model: "ScaleShiftMACE"
compute_stress: True
compute_forces: True
clip_grad: 10
error_table: PerAtomRMSE
lr: 0.001
scaling: rms_forces_scaling
batch_size: 16
max_num_epochs: 10
ema: True
ema_decay: 0.9999
#save_all_checkpoints: True
##scheduler_patience: 5
patience: 50
amsgrad: True
default_dtype: float64
device: cpu  
restart_latest: True
seed: 2025
keep_isolated_atoms: True
#keep_checkpoints: True
save_cpu: True
weight_decay: 1e-8
eval_interval: 1
enable_cueq: True
